title = "Federico Leva"
baseURL = "https://federicoleva.eu/"
copyright = "Creative Commons BY-SA 4.0"
#MetaDataFormat = "yaml"
# Remember to delete the useless JS from data/webpack_assets.json
theme = "ananke"
# hugo-theme-nix, minimal

#languageCode = "en"
DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
# Also use HUGO_ENV="production" hugo
enableRobotsTXT = false

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  featured_image = "/images/vuosaari-cigno.jpg"
  recent_posts_number = 0
  background_color_class = "bg-black"
  mastodon = "https://mamot.fr/@nemobis"
  linkedin = "https://www.linkedin.com/in/federicoleva"
  gitlab = "https://www.openhub.net/accounts/nemobis"

[Languages]
[Languages.en]
  weight = 3
  description = "Federico Leva: free knowledge and digital rights"
[Languages.it]
  weight = 2
  description = "Federico Leva: conoscenza libera e diritti digitali"
[Languages.fi]
  weight = 1
  description = "Federico Leva: vapaa tieto ja digitaaliset oikeudet"
